### ISSUE TITLE
error: ‘std::shared_ptr’ has not been declared    31 |     void addTranscoder(std::shared_ptr<TransCoder> transcoder);

### ISSUE THREAD

**Issue by GabrielRMx** [icetd/CamRtspServer#1]
I was following the steps of the readme but its not compiling

**Comment by icetd** [comment]
Can you provide more compilation logs?

**Comment by icetd** [comment]
Make sure your gcc version is newer

**Comment by icetd** [comment]
The header file memory may not be added, I added it https://github.com/icetd/CamRtspServer/commit/c802a280ed54c40054f725c0a189eb2f0ef8fe64
